on: [push, pull_request]
name: CI
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.0-beta1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: |
        # go vet ./...
        go test -v -race ./...
        go test -bench=.
    - name: Force update to pkg.go.dev
      run: |
        # Refresh latest tag.
        curl https://sum.golang.org/lookup/github.com/deckarep/golang-set@$(git describe --tags `git rev-list --tags --max-count=1`)
